trigger:
- main

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: NuGetCommand@2
  displayName: 'Pack the NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BuildVersion'

- task: NuGetAuthenticate@0
  displayName: 'Authenticate with Azure Artifacts'
  inputs:
    artifactFeeds: 'class-library-projects-packages'

- task: NuGetCommand@2
  displayName: 'Push the NuGet package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'