trigger:
- main

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $env:MY_PACKAGE_VERSION = '1.0.0'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: NuGetCommand@2
  displayName: 'Pack the NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'

- task: NuGetAuthenticate@0
  displayName: 'Authenticate with Azure Artifacts'
  inputs:
    artifactFeeds: 'class-library-projects-packages'
